export enum RankingItemRaceEventType {
    NPC = 'NPC',
    USER_ACTIVITY = 'USER_ACTIVITY',
    USER_OLD_ACTIVITY = 'USER_OLD_ACTIVITY',
    OTHER_USER_ACTIVITY = 'OTHER_USER_ACTIVITY',
    OTHER_USER_OLD_ACTIVITY = 'OTHER_USER_OLD_ACTIVITY'
}