apiVersion: v1
kind: Service
metadata:
  name: sport-activity-comparison-backend
  namespace: "sport-activity"
  labels:
    app: sport-activity-comparison-backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: sport-activity-comparison-backend